config/routes.rb
Rails.application.routes.draw do
  resources :portfolio_pieces
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # get 'index'
  root 'home#index'

  get '/about_me', to: 'about_me#index'

  get '/portfolio', to: 'portfolio#index'

  get '/connect', to: 'connect#index'

  get '/blog', to: 'blog#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio_piece.rb
class PortfolioPiece < ApplicationRecord
end

app/controllers/about_me_controller.rb
class AboutMeController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/connect_controller.rb
class ConnectController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end
end

app/controllers/portfolio_pieces_controller.rb
class PortfolioPiecesController < ApplicationController
  before_action :set_portfolio_piece, only: [:show, :edit, :update, :destroy]

  # GET /portfolio_pieces
  # GET /portfolio_pieces.json
  def index
    @portfolio_pieces = PortfolioPiece.all
  end

  # GET /portfolio_pieces/1
  # GET /portfolio_pieces/1.json
  def show
  end

  # GET /portfolio_pieces/new
  def new
    @portfolio_piece = PortfolioPiece.new
  end

  # GET /portfolio_pieces/1/edit
  def edit
  end

  # POST /portfolio_pieces
  # POST /portfolio_pieces.json
  def create
    @portfolio_piece = PortfolioPiece.new(portfolio_piece_params)

    respond_to do |format|
      if @portfolio_piece.save
        format.html { redirect_to @portfolio_piece, notice: 'Portfolio piece was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio_piece }
      else
        format.html { render :new }
        format.json { render json: @portfolio_piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolio_pieces/1
  # PATCH/PUT /portfolio_pieces/1.json
  def update
    respond_to do |format|
      if @portfolio_piece.update(portfolio_piece_params)
        format.html { redirect_to @portfolio_piece, notice: 'Portfolio piece was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_piece }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_pieces/1
  # DELETE /portfolio_pieces/1.json
  def destroy
    @portfolio_piece.destroy
    respond_to do |format|
      format.html { redirect_to portfolio_pieces_url, notice: 'Portfolio piece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio_piece
      @portfolio_piece = PortfolioPiece.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_piece_params
      params.require(:portfolio_piece).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolio_pieces_helper.rb
module PortfolioPiecesHelper
end

app/views/about_me/index.html.erb
<head>
	<title>LilMissMoffitt - About Me</title>
</head>
<body>
	<div class="indent">
		<h1>What I am Doing...</h1>
			<p> I am currently attending Utah Valley University working to get my bachelor's degree in Computer Science. While I am not at school I am studying programming languages and working on personal projects, such as this website! I am also attending a mentorship hosted by the Engineering department at my work, Acima Credit LLC. Here, I get to shadow Engineers and see what it's like behind the scenes. I have found this program to be very beneficial, as I have learned problem solving skills and other software/resources that are not traditionally taught.<br><br> I am currently studying JavaScript, Ruby on Rails, and anything else that may come up along the way!</p>
		<h1>How I Got Here...</h1>
			<p>I have taken an Introductory to Jave class through SLCC. I have also taken the HTML, CSS, and Ruby courses through <a class="text_link" href="https://www.codecademy.com/" target="_blank">Codecademy</a>. I am working through the Complete Web Developer 2.0 course through <a class="text_link" href="https://www.udemy.com/" target="_blank">Udemy</a>. </p>
		<h1>Where I am Going...</h1>
			<p>I am an aspiring web developer. I love to bring minimal and nature inspired designs into technology. I am here to solve problems and make life easier, by making efficient and reliable systems. </p>

	<!-- 	<img class="profile_picture" src="../../assets/images/Melissa.jpg" height="100" width="100"> -->
		<div class="profile_picture"></div>
	</div>
</body>

app/views/blog/index.html.erb
<head>
  <title>LilMissMoffitt - Blog</title>
</head>
<iframe id="blog"width="1400" height="800" src="https://lilmissmoffitt.weebly.com/blog" frameborder="0"></iframe>

app/views/connect/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LilMissMoffitt - Connect</title>  

  <meta charset="utf-8"/>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale-1"/>
  <link rel="stylesheet" type="text/css" href="../css/styles.css"> 
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Great+Vibes|IBM+Plex+Sans&display=swap" rel="stylesheet">

</head>
<body>
 <div class="connect_background"> 
    <div class="connect_form">
      <h1>CONNECT WITH ME</h1>

      <form>
        <p class="connect_form_elements"><input type="text" name = "fn" placeholder="First Name">
        <input type="text" name ="ln"placeholder="Last Name">
        </p>
        <p class="connect_form_elements"><input type="text" name="email" placeholder="example@email.com"> 
        </p>
        
       <!--  <form method="get" ID="contact_message">
        </form> -->
          <textarea class= "connect_form_elements" form="contact_message" name="contactmessage" id="cmid" cols="35" wrap="soft" placeholder="Type message here"></textarea> <br>
        <input type="submit"/>
      </form>
    </div>
  </div>
</body>

</html>

app/views/home/index.html.erb
<head>
  <title>LilMissMoffitt - Home</title>
</head>
<div class="background_image">  </div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Great+Vibes|IBM+Plex+Sans|Raleway&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="top"></p>
  <div class="page_titles">
    <h1 ID="title">MELISSA MOFFITT</h1>
    <h3 ID="subtitle">lilmissmoffitt</h3>
  </div>
  <hr>
    
  <div id="Navbar">
    
      <%= link_to "HOME", root_path, class: "buttons" %> 
      <%= link_to "ABOUT ME", about_me_path, class: "buttons" %>
      <%= link_to "PORTFOLIO", portfolio_path, class: "buttons" %> 
      <%= link_to "CONNECT", connect_path, class: "buttons" %> 
      <%= link_to "BLOG", blog_path, class: "buttons" %>  
     
  </div>
  <hr>
    <%= yield %>

    <footer></footer>
  </body>
</html>

app/views/portfolio/index.html.erb
<link href="css/bootstrap.css" rel="stylesheets">
<head>
	<title>LilMissMoffitt - Portfolio</title>
</head>
<body>
  <div class="indent">
		<h1> Development </h1>
		<div class="outside_the_office">
		  <h1> Outside The Office </h1>
				<!-- <div class="row"> -->
					<div class="column">
						<%= image_tag "Outdoors/IMG_5497.jpg" %>
						<%= image_tag "Outdoors/IMG_5436.jpg" %>
						<%= image_tag "Outdoors/IMG_5438.jpg" %>
				  </div>
				  <div class="column">
					  <%= image_tag "Outdoors/IMG_5501.jpg" %>
					  <%= image_tag "Outdoors/IMG_5505.jpg" %>
					  <%= image_tag "Outdoors/IMG_5508.jpg" %>
				  </div>
				  <div class="column">
					  <%= image_tag "Outdoors/IMG_5796.jpg" %>
					  <%= image_tag "Outdoors/IMG_5872.jpg" %>
					  <%= image_tag "Outdoors/IMG_5876.jpg" %>
				  </div>
				  <div class="column">
					  <%= image_tag "Outdoors/IMG_5330.jpg" %>
					  <%= image_tag "Outdoors/IMG_5775.jpg" %>
					  <%= image_tag "Outdoors/IMG_5887.jpg" %>
				  </div>
				  <div class="column">
					  <%= image_tag "Outdoors/IMG_5972.jpg" %>
					  <%= image_tag "Outdoors/IMG_5973.jpg" %>
					  <%= image_tag "Outdoors/IMG_5974.jpg" %>
				  </div>
			 <!--  </div> -->
			</div>
		<h1> Creating </h1>
  </div>
</body>

app/views/portfolio_pieces/_form.html.erb
<%= form_with(model: portfolio_piece, local: true) do |form| %>
  <% if portfolio_piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio_piece.errors.count, "error") %> prohibited this portfolio_piece from being saved:</h2>

      <ul>
      <% portfolio_piece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolio_pieces/edit.html.erb
<h1>Editing Portfolio Piece</h1>

<%= render 'form', portfolio_piece: @portfolio_piece %>

<%= link_to 'Show', @portfolio_piece %> |
<%= link_to 'Back', portfolio_pieces_path %>

app/views/portfolio_pieces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portfolio Pieces</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolio_pieces.each do |portfolio_piece| %>
      <tr>
        <td><%= portfolio_piece.title %></td>
        <td><%= portfolio_piece.body %></td>
        <td><%= link_to 'Show', portfolio_piece %></td>
        <td><%= link_to 'Edit', edit_portfolio_piece_path(portfolio_piece) %></td>
        <td><%= link_to 'Destroy', portfolio_piece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio Piece', new_portfolio_piece_path %>

app/views/portfolio_pieces/new.html.erb
<h1>New Portfolio Piece</h1>

<%= render 'form', portfolio_piece: @portfolio_piece %>

<%= link_to 'Back', portfolio_pieces_path %>

app/views/portfolio_pieces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong class="title">Title:</strong>
  <%= @portfolio_piece.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @portfolio_piece.body %>
</p>

<%= link_to 'Edit', edit_portfolio_piece_path(@portfolio_piece) %> |
<%= link_to 'Back', portfolio_pieces_path %>